#!/bin/sh
# Source of truth for git dp / dpp… / dps / dsp…
# Edit this, re-run. Writes alias.dp.gitconfig beside this script.
set -eu

max=18

here=$(CDPATH= cd -- "$(dirname "$0")" && pwd)
out=$here/alias.dp.gitconfig
tmp=$out.tmp

pchars() {
  k=0
  s=
  while [ "$k" -lt "$1" ]; do
    s="${s}p"
    k=$((k + 1))
  done
  printf '%s' "$s"
}

# $1 name, $2 lg rev, $3 diff args after --stat
emit_stat() {
  printf '\t%s = "!f() { git --no-pager lg -1 %s && echo && git -c core.pager=cat diff --stat %s \\"$@\\"; }; f"\n' \
    "$1" "$2" "$3"
}

{
  printf '%s\n' '# Generated by gen-dp-aliases.sh. Do not edit.'
  printf '%s\n' "# max=${max}"
  printf '%s\n' '[alias]'
  n=1
  while [ "$n" -le "$max" ]; do
    p=$(pchars "$n")
    if [ "$n" -eq 1 ]; then
      printf '\t%s = diff --diff-filter=MRA HEAD^\n' "d${p}"
      # n=1 stat is working tree vs HEAD^, no --diff-filter (old dps/dsp).
      emit_stat "d${p}s" HEAD 'HEAD^'
      emit_stat "ds${p}" HEAD 'HEAD^'
    else
      prev=$((n - 1))
      printf '\t%s = diff --diff-filter=MRA HEAD~%s HEAD~%s\n' "d${p}" "$n" "$prev"
      emit_stat "d${p}s" "HEAD~${prev}" "--diff-filter=MRA HEAD~${n} HEAD~${prev}"
      emit_stat "ds${p}" "HEAD~${prev}" "--diff-filter=MRA HEAD~${n} HEAD~${prev}"
    fi
    n=$((n + 1))
  done
} > "$tmp"

mv "$tmp" "$out"
